name: Rust

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: sudo apt-get install libatk1.0-0 libgtk-3-dev libgtk-3-0 libgtk-layer-shell0 libgtk-layer-shell-dev gir1.2-gtklayershell-0.1

      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --profile release-lto --verbose

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: |
            target/release-lto/tehda
    # - name: Run tests
    #   run: cargo test --verbose
